version: '3.8'

services:
  dind-container:
    image: docker:20-dind
    privileged: true
    networks:
      - jenkins_home
    volumes:
      - /var/lib/docker

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
    depends_on:
      - dind
    environment:
      - DOCKER_HOST=tcp://dind-container:2376

networks:
  jenkins_home:

volumes:
  jenkins-data: